name: Set Script Permissions

on:
  push:
    branches: [main]

jobs:
  set-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set execute permission
        run: chmod +x build.sh
        
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add build.sh
          git commit -m "Set execute permissions" || echo "No changes to commit"
          git push